# Generated by Django 4.2.6 on 2023-10-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_player',
            field=models.BooleanField(default=0),
        ),
    ]
