# Generated by Django 4.2.6 on 2023-10-25 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_character_is_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('S', 'Speech'), ('B', 'Battle')], max_length=1)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='current_process',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('event_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eventgroup')),
            ],
        ),
    ]
