# Generated by Django 4.2.6 on 2023-10-25 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_eventgroup_character_current_process_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.character'),
            preserve_default=False,
        ),
    ]
