# Generated by Django 4.2.6 on 2023-10-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sub_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
