# Generated by Django 4.2.6 on 2023-10-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_sub_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_sub_process',
            field=models.IntegerField(default=0),
        ),
    ]
