# Generated by Django 4.2.6 on 2023-10-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_character_current_sub_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('attack', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='current_process',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='current_sub_process',
            field=models.IntegerField(default=1),
        ),
    ]
