# Generated by Django 4.2.6 on 2023-10-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_item_image_characteritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='max_item',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/item_images/'),
        ),
    ]
