# Generated by Django 4.2.6 on 2023-10-30 16:53

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_characteritem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='jump_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jump_to', to='main.eventgroup'),
        ),
        migrations.AlterField(
            model_name='event',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.character'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_group',
            field=models.ForeignKey(default=main.models.find_last_order, on_delete=django.db.models.deletion.CASCADE, to='main.eventgroup'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sub_order',
            field=models.IntegerField(default=main.models.find_last_sub_order),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='type',
            field=models.CharField(choices=[('S', 'Speech'), ('B', 'Battle'), ('C', 'Choice')], max_length=1),
        ),
    ]
