# Generated by Django 4.2.6 on 2023-10-30 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_event_jump_to_alter_event_character_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='jump_to',
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
                ('jump_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jump_to', to='main.eventgroup')),
            ],
        ),
    ]
