# Generated by Django 4.2.6 on 2023-10-30 18:58

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_event_jump_to_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='jump_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jump_to', to='main.event'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='order',
            field=models.IntegerField(default=main.models.find_last_group),
        ),
    ]
