# Generated by Django 4.2.6 on 2023-10-30 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_choice_jump_to_alter_eventgroup_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='jump_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jump_to', to='main.eventgroup'),
        ),
    ]
