# Generated by Django 4.2.6 on 2023-12-22 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='jump_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jump_to_from_event', to='main.eventgroup'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='jump_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jump_to_from_choice', to='main.eventgroup'),
        ),
    ]
