# Generated by Django 4.2.6 on 2023-12-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='max_atk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='min_atk',
            field=models.IntegerField(default=0),
        ),
    ]
