# Generated by Django 4.2.6 on 2023-12-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_skill_max_atk_skill_min_atk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='hp',
            new_name='current_hp',
        ),
        migrations.AddField(
            model_name='character',
            name='max_hp',
            field=models.FloatField(default=0),
        ),
    ]
