# Generated by Django 4.2.6 on 2023-12-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_event_p2'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='round',
            field=models.IntegerField(default=1),
        ),
    ]
