# Generated by Django 4.2.6 on 2023-12-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_skill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='p2_act',
            field=models.BooleanField(default=False),
        ),
    ]
