# Generated by Django 4.2.6 on 2023-12-23 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_event_p2_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='victory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jump_to_if_victory', to='main.eventgroup'),
        ),
    ]
