# Generated by Django 4.2.6 on 2023-12-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_skill_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jump_to_if_lose', to='main.eventgroup'),
        ),
    ]
