# Generated by Django 4.2.6 on 2023-12-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_event_lose'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='finish',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
