# Generated by Django 4.2.6 on 2023-12-27 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        ('main', '0029_character_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_choice', to='club.club'),
        ),
    ]
