# Generated by Django 4.2.6 on 2024-01-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_skill_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
